Scrum 5 user profile management
ASE-FS24/user-manager pull request #8
Opened 2024-03-31 19:43 UTC by ovanov

Enable basic user profile update functionality.
[SCRUM-29: provide basic user profile update and delete functionality](https://github.com/ASE-FS24/user-manager/commit/8db128d682be20781e06a461ce1c828d3f319c76) 
- extend UserController and UserService
- extend UserControllerTest and UserServiceTest
- write basic DynamoDB test in UserInfoIntegrationTest
- remove unused value in user.yaml
[SCRUM-29: provide upload and retrieve profile picture functionality](https://github.com/ASE-FS24/user-manager/commit/2e4b146fdcf5542b53e4831d5d1ce2bbda73d4bb)
- Upload profile pictures to s3 bucket and retrieve them per user

2024-04-03 13:02 UTC, krwro requested changes
Good job. I have some minor suggestions in the comments.

2024-04-03 13:02 UTC, krwro commented on src/main/java/ch/nexusnet/usermanager/controller/UserController.java
> +        }
Instead of catching exceptions in the controller, use an exception handler class with the @ControllerAdvice annotation. That way, you can better separate concerns regarding error handling and reduce the boilerplate code in the controller. (See post manager's GlobalExceptionHandler class, or https://zetcode.com/springboot/controlleradvice/)

2024-04-03 13:02 UTC, krwro commented on src/main/java/ch/nexusnet/usermanager/service/UserService.java
> +        String userInformationMessage = getUserNotFoundByUserNameMessage(userInfo.get().getUsername());
getUserNotFoundByUserNameMessage. Wrong message: it says the user with username was not found when getting the user, which is not a problem when creating a user. Should be User with username already exists

2024-04-03 13:02 UTC, krwro commented on src/main/java/ch/nexusnet/usermanager/service/UserService.java
>          return userInfoRepository.findById(userId);
If you have this method, consider making it return UserInfo and put the user not found error logic here. So you would have the following here (pseudocode):
        if (optionalUserInfo.isEmpty()) {
            String userInformationMessage = getUserNotFoundByIdMessage(userId);
            log.info(userInformationMessage);
            throw new UserNotFoundException(userInformationMessage);
        } else {return optionalUserInfo.get()}

This makes it so you have the "no user found info" in one place, instead of multiple as you do now. That way you could even get rid of the getUserNotFoundByIdMessage method because it would only be used here, but feel free to leave it. in.

2024-04-03 13:02 UTC, krwro commented on src/main/java/ch/nexusnet/usermanager/service/UserService.java
>          throw new UserNotFoundException(userInformationMessage);
see comment below

2024-04-03 13:02 UTC, krwro commented on src/main/java/ch/nexusnet/usermanager/service/UserService.java
> +        }
see comment below

2024-04-03 13:02 UTC, krwro commented on src/main/java/ch/nexusnet/usermanager/service/UserService.java
> +        return userInfos.stream().findAny();
Same as findUserById, I would move error handling here.

2024-04-03 13:02 UTC, krwro commented on src/main/java/ch/nexusnet/usermanager/service/UserService.java
>          return userInfoRepository.findById(userId);
In the post manager I do the following:
 ```
dynamoDBCommentRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Comment with id " + id + " not found"));
```
Which is just one line, but it does not log it. (Logging could be done in GlobalExceptionHandler instead or using Aspect Oriented Programming (AOP) annotations) I haven't implemented logging in the post manager yet, but I will use AOP. For now do it how you want it.

2024-04-03 13:02 UTC, krwro commented on src/main/java/ch/nexusnet/usermanager/service/UserService.java
> +    private void throwExeptionIfUserDoesNotExist(String userId) throws UserNotFoundException {
Ah, here you have factorized the "user not found" logic. I saw this after writing the first comment on it. Still, as mentioned earlier, I would incorporate it with findUserById.

2024-04-03 13:02 UTC, krwro commented on src/test/java/ch/nexusnet/usermanager/aws/dynamodb/model/table/UserInfoIntegrationTest.java
> +        "amazon.aws.secretkey=test231" })
Is this necessary if you have an application.properties file for tests?

2024-04-03 15:07 UTC, ovanov commented on src/main/java/ch/nexusnet/usermanager/controller/UserController.java
> +        }
I really like that (did not know about that), but this seems like quite some refactoring. I'd suggest taking this up for the next sprint, due to time reasons. What do you think?

2024-04-03 15:09 UTC, ovanov commented on src/main/java/ch/nexusnet/usermanager/service/UserService.java
> +        String userInformationMessage = getUserNotFoundByUserNameMessage(userInfo.get().getUsername());
good catch

2024-04-03 15:31 UTC, ovanov commented on src/main/java/ch/nexusnet/usermanager/service/UserService.java
>          return userInfoRepository.findById(userId);
Good suggestion. I will implement that for all methods except the `findUserByUserName`method. This has to stay optional.

2024-04-03 15:32 UTC, ovanov commented on src/main/java/ch/nexusnet/usermanager/service/UserService.java
> +        return userInfos.stream().findAny();
Good suggestion. I will implement that for all methods except the findUserByUserNamemethod. This has to stay optional.

2024-04-03 18:09 UTC, krwro commented on src/main/java/ch/nexusnet/usermanager/controller/UserController.java
> +        }
Sure. Let us do it next sprint

2024-04-04 07:24 UTC, krwro approved these changes

2024-04-04 09:29 UTC, krwro commented on src/test/java/ch/nexusnet/usermanager/aws/s3/client/S3ClientTest.java
> +    void testUploadProfilePictureToS3WithNotSupportedMimeTypes_expectSuccess(String contentType) throws IOException {
Wrong name: Should be expectException

2024-04-04 10:36 UTC, merged